fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: v9.7.0
    inifile:
      repo: "https://github.com/puppetlabs/puppetlabs-inifile.git"
      ref: v6.2.0
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: v10.0.1
  symlinks:
    cockpit: "#{source_dir}"
