fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: 4.11.0
    inifile:
      repo: "git://github.com/puppetlabs/puppetlabs-inifile.git"
      ref: 1.5.0
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: 2.3.0
  symlinks:
    cockpit: "#{source_dir}"
